/** @format */

import { BUTTON_ENUM } from "../../enum";

export const NUMBERS = [
	BUTTON_ENUM.ZERO,
	BUTTON_ENUM.ONE,
	BUTTON_ENUM.TWO,
	BUTTON_ENUM.THREE,
	BUTTON_ENUM.FOUR,
	BUTTON_ENUM.FIVE,
	BUTTON_ENUM.SIX,
	BUTTON_ENUM.SEVEN,
	BUTTON_ENUM.EIGHT,
	BUTTON_ENUM.NINE,
];
